version: 2
jobs:
  build:
    working_directory: ~/java-task-therading/
    docker:
      - image: maven:3.5
    steps:
      - checkout

      # Test
      - restore_cache:
          key: MAVEN
      - run:
          name: Maven Compile
          command: mvn compile
      - run:
          name: Maven Test
          command: mvn test
      - save_cache:
          key: MAVEN
          paths:
            - ~/.m2/
